# Generated by Django 4.2.1 on 2023-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('was_rain', models.BooleanField()),
                ('forecast_mm', models.FloatField()),
                ('precip_mm', models.FloatField()),
                ('rain_chance', models.IntegerField()),
            ],
        ),
    ]
