# Generated by Django 4.2.1 on 2023-06-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cityweather_no_course_cityweather_yes_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityweather',
            name='city_id',
        ),
    ]
