# Generated by Django 4.2.1 on 2023-06-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_appuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='balance',
            field=models.FloatField(default=1000),
        ),
    ]
