# Generated by Django 4.2.1 on 2023-06-18 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appuser_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('bet_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('bet_type', models.BooleanField()),
                ('amount', models.FloatField()),
                ('reward', models.FloatField()),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cityweather')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
